easy_admin:
    site_name: Symfony Test

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { entity: 'Slider', label: 'Slider', icon: 'map-marker' }

    entities:
        Slider:
            class: App\Entity\Slider
#            fields:
#                - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-7'}
#                - title
#                - {property: 'content', type: 'text_editor'}
#                - createdAt
#                - published
#                - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-5'}
#                - category
#                - tags
#                - {type: 'group', icon: 'clip', label: 'Attachments', css_class: 'col-lg-5'}
#                - { property: 'thumbnailFile', type: 'vich_image' }
            form:
                fields:
                    - { property: 'backgroundFile', type: 'vich_image'}
                    - title
                    - text
                    - buttonName
                    - buttonUrl
                    - isUsed
            list:
                fields:
                    - title
                    - text
                    - buttonName
                    - buttonUrl
                    - isUsed
                    - { property: 'background', type: 'image', 'base_path': "uploads/slider", label: 'Photo' }
                sort: [ 'createdAt', 'ASC' ]
            edit:
                fields:
                    - '-tags'