easy_admin:
    site_name: Avon

    design:
        menu:
            - { route: 'homepage', label: 'Повернутися до сайиу', icon: 'home' }
            - { entity: 'Slider', label: 'Слайдер', icon: 'sliders' }
            - { entity: 'Catalog', label: 'Каталог', icon: 'book' }

    entities:
        Slider:
            class: App\Entity\Slider
            form:
                fields:
                    - { property: 'backgroundFile', type: 'vich_image'}
                    - { property: 'title', label: 'Заголовок' }
                    - { property: 'text', label: 'Текст' }
                    - { property: 'buttonName', label: 'Назва кнопки' }
                    - { property: 'buttonUrl', label: 'Url адреса' }
                    - { property: 'isUsed', label: 'Використати' }
            list:
                fields:
                    - { property: 'title', label: 'Заголовок' }
                    - { property: 'text', label: 'Текст' }
                    - { property: 'buttonName', label: 'Назва кнопки' }
                    - { property: 'buttonUrl', label: 'Url адреса' }
                    - { property: 'isUsed', label: 'Використати' }
                    - { property: 'background', type: 'image', 'base_path': "uploads/slider", label: 'Фото' }
                sort: [ 'createdAt', 'ASC' ]
            edit:
                fields:
                    - '-tags'
        Catalog:
            class: App\Entity\Catalog
            form:
                fields:
#                    - { property: 'catalogFile', type: 'vich_image', type_options: { required: true }, label: 'Каталог'}
                    - { property: 'catalogFile', type: 'vich_image', label: 'Каталог'}
                    - { property: 'titleImageFile', type: 'vich_image', type_options: { required: true }, label: 'Титульна сторінка'}
                    - { property: 'catalogDate', type: 'date', type_options: { format: 'd-M-y' }, label: 'Початок дії каталога' }
            list:
                fields:
                    - { property: 'titleImage', type: 'image', 'base_path': "uploads/catalog", label: 'Титульна сторінка' }
                    - { property: 'catalogDate', type: 'date', type_options: { format: 'd-M-y' }, label: 'Початок дії каталога' }
                sort: [ 'createdAt', 'ASC' ]
            edit:
                fields:
                    - { property: 'catalogDate', type: 'date', type_options: { format: 'd-M-y' }, label: 'Початок дії каталога' }